ci: add integration tests to github action yaml
twonote/solid-file-python pull request #28
Opened 2022-02-02 23:39 UTC by peter0083

- add steps to run:
  -  Solid Authorization tests
  -  Solid API tests

2022-03-02 09:07 UTC, hrchu requested changes

2022-03-03 04:17 UTC, peter0083 commented on .github/workflows/continuous-integration.yml
> +      matrix: # matrix testing strategy
Noted. Thank you for the review and feedback @hrchu . On which version should we run the integration test? Python 3.9? or Python 3.10?

2022-03-03 06:45 UTC, hrchu requested changes

2022-03-03 06:45 UTC, hrchu commented on .github/workflows/continuous-integration.yml
> +      matrix: # matrix testing strategy
anything you say😆

2022-03-04 04:58 UTC, peter0083 commented
thanks @hrchu, then let's do "the latest and hottest Python version minus one": Python 3.9.

2022-03-04 07:30 UTC, hrchu commented
> thanks @hrchu, then let's do "the latest and hottest Python version minus one": Python 3.9.

Good idea!

2022-03-04 07:30 UTC, merged